### PR TITLE
add `is_roman_numeral` func

### PR DESCRIPTION
**Pull request by AndrewBasem1**
## Additions
Adding `is_roman_numeral` function to `roman.py` file

## Why?
This is a helpful function that can be used to check if an input string is a valid roman numeral or not ^_^

### CODE REVIEW

**Comment by AndrewBasem1** [comment]
I realize this still needs to accomdate the CLI args, just pushing the simplest commit to check if you are open to PRs or not

**Comment by dataflake** [comment]
This project is open to PRs, but there's a few issues:

- You need to sign the contributor agreement first, see https://www.zope.dev/developer/becoming-a-committer.html
- The code fails linting (see https://github.com/zopefoundation/roman/actions/runs/4442607375/jobs/7802948812?pr=14)
- There is no unit test for it
- There is no change log entry

**Comment by AndrewBasem1** [comment]
@dataflake thank you for reviewing my PR, Please check the following changes:
1. **fixed linting errors** &rarr; please rerun the checks again
2. **Added changes to `Changes.txt`** &rarr; please review the edit to that file

regarding the unit tests, can you offer some assist on how to start on those? haven't done them before ^_^
I'll sign the agreement later before merging as I don't have access to a printer right now

Thank you

**Comment by dataflake** [comment]
@AndrewBasem1 The tests will run automatically whenever you make a push. The linting tests are still failing.

You can add test methods to the test class `TestRoman` in the `tests.py` module. The existing tests should make it clear how you call the method or function you want to test with various argument values and then test the return value with the different `assert` methods.

**Comment by icemac** [comment]
Are there any news for this PR otherwise I'd like to close it if there is no interest or steam to complete it.

**Pull request closed without merging**
